import pg from 'pg';
import fs from 'fs';
const env = fs.readFileSync('web/.env.local','utf8');
const url = env.split('\n').find(l=>l.startsWith('DATABASE_URL='))?.slice(13).trim();
const c = new pg.Client({connectionString:url, options:'-c timezone=UTC'});
await c.connect();
const q = async (label,sql)=>{const r=await c.query(sql);console.log('==='+label);console.table(r.rows);};
await q('target rows', `select slug, segment, offering_type, open_date::date, close_date::date, listing_date::date, price_range_min, price_range_max, issue_size, status from ipos where slug in ('mopshop-distribution-ltd','priority-jewels-ltd','suryo-trading-ltd','travels-rentals-ltd') or slug ilike '%mopshop%' or slug ilike '%priority-jewel%' or slug ilike '%suryo%' or slug ilike '%travels%rental%'`);
await q('SME+FPO remaining', `select count(*)::int as n from ipos where segment='SME' and offering_type='FPO'`);
await q('SME+FPO list', `select slug, offering_type from ipos where segment='SME' and offering_type='FPO' limit 20`);
await c.end();
