// Self-test for scripts/ci/check-design-traceability.mjs (OD-52, §8.5).
// Each case below builds a tiny fixture tree in a temp dir and runs the REAL
// check script against it via a child process — the test never re-implements
// the check's parsing logic. Slice s1 covered failure modes 1-3. Slice s2
// (this file) adds mode 4 — a rule's hash changed at the same id, with
// neither its owning card nor a declaring test in the pull request diff.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(__dirname, '..', 'check-design-traceability.mjs');
// Repo root, for the one case that runs against the real files.
const REPO_ROOT = join(__dirname, '..', '..', '..');

// This test file lives under scripts/ci/tests/, one of the check's own real
// scan roots — so a literal "// implements: R-xxx" string embedded verbatim
// in this source would be picked up by the check when it later scans the
// REAL repo (the last test case below runs the check against real files).
// Build the header out of parts so the raw source never contains the
// contiguous "// implements:" substring; the runtime STRING VALUE written to
// each fixture file is still exactly that text.
const IMPLEMENTS_TAG = ['/', '/', ' implements: '].join('');

function writeFile(root, relPath, content) {
  const full = join(root, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

function mkFixtureRoot() {
  return mkdtempSync(join(tmpdir(), 'design-traceability-'));
}

function rulesJson(rules) {
  return JSON.stringify({ rules }, null, 2);
}

function rule(id, opts = {}) {
  return {
    id,
    hash: opts.hash || 'deadbeef0000',
    section: opts.section || '1.1 Fixture section',
    kind: opts.kind || 'prose',
    text: opts.text || 'A fixture rule.',
    first_seen: '2026-09-10',
    retired: !!opts.retired,
  };
}

function cardBody(idsLine) {
  return (
    '# Item 99 — fixture card\n\n' +
    '## Rules implemented\n\n' +
    '<!-- generated by docs/design/apply-rule-ownership.mjs - edits inside this block are overwritten -->\n\n' +
    '1 rule(s) from `docs/design/rules.json`.\n\n' +
    '| Design section | Rule ids |\n' +
    '|---|---|\n' +
    '| §1.1 | ' +
    idsLine +
    ' |\n\n' +
    '## Known gaps\n\n' +
    'None.\n'
  );
}

function runCheck(root, extraArgs = []) {
  return spawnSync(
    'node',
    [
      SCRIPT,
      '--rules',
      join(root, 'docs/design/rules.json'),
      '--cards',
      join(root, 'docs/design/build-cards'),
      '--unclaimed',
      join(root, 'docs/design/rules-unclaimed.json'),
      '--tests',
      join(root, 'tests'),
      ...extraArgs,
    ],
    { encoding: 'utf8' }
  );
}

test('mode 1: a live rule claimed by no card and not unclaimed -> exit 1, names the id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-001')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-999-not-real'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing here\n');

    const res = runCheck(root);
    assert.equal(res.status, 1, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /R-001/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 2: a card claims an id no test declares -> exit 0 (reporting mode), names card + id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-002')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-002'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing declared here\n');

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.match(res.stdout, /R-002/);
    assert.match(res.stdout, /item-99-fixture\.md/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 3: a test declares R-999 which is not live -> exit 1, names the test file + id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-003')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-003'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/bar.test.mjs', IMPLEMENTS_TAG + 'R-003, R-999\n');

    const res = runCheck(root);
    assert.equal(res.status, 1, res.stdout + res.stderr);
    const out = res.stdout + res.stderr;
    assert.match(out, /R-999/);
    assert.match(out, /bar\.test\.mjs/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('self-guard: zero live rules is a FAIL, never a pass -> exit 2', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-004', { retired: true })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-004'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-004\n');

    const res = runCheck(root);
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /zero live rules/i);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('Finding 2 regression: summary line names the roots scanned, not just a count', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-050')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-050'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-050\n');

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    // The summary must carry the identity of the scanned root(s) — a bare
    // count regresses to the class this rule bars (signal-ownership.md R1).
    // A future edit that swaps the root NAMES for a digit count must turn
    // this test RED.
    const match = res.stdout.match(/test roots scanned: (.+)$/m);
    assert.ok(match, `no "test roots scanned:" segment in:\n${res.stdout}`);
    const scanned = match[1].trim();
    assert.ok(
      !/^\d+$/.test(scanned),
      `expected the scanned root NAMES, got what looks like a bare count: "${scanned}"`
    );
    // The fixture's only test root ends in "tests" — its name must survive
    // into the summary line verbatim, not be collapsed to a number.
    assert.match(scanned, /tests$/, `expected the root path to end in "tests", got: "${scanned}"`);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('clean fixture tree -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-005'), rule('R-006', { retired: true })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-005'));
    writeFile(
      root,
      'docs/design/rules-unclaimed.json',
      JSON.stringify({ unclaimed: { 'R-007': 'not a real rule, just proving unclaimed is honored' } })
    );
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-005\n');

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MAJOR 1 regression: zero surviving test roots -> exit 2, never a silent PASS', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-777')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-777'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    // Deliberately do NOT create the tests root — this reproduces the
    // reviewer's finding: `--tests <nonexistent>` used to print
    // "1 rules, 1 claimed, 0 orphans ... PASS" and exit 0, silently
    // disarming mode 3 for the whole population of test declarations.
    const res = spawnSync(
      'node',
      [
        SCRIPT,
        '--rules',
        join(root, 'docs/design/rules.json'),
        '--cards',
        join(root, 'docs/design/build-cards'),
        '--unclaimed',
        join(root, 'docs/design/rules-unclaimed.json'),
        '--tests',
        join(root, 'tests-does-not-exist'),
      ],
      { encoding: 'utf8' }
    );
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /zero test roots/i);
    assert.match(res.stdout + res.stderr, /tests-does-not-exist/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MAJOR 2 regression: heading anchor recognises the real heading even when prose mentions it first', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-050')]));
    // Mirrors the real item-19 card bug: prose ABOVE the real heading
    // mentions the heading text in backticks, mid-document, before the
    // actual "## Rules implemented" heading. A plain indexOf() finds the
    // prose mention instead of the real heading and loses the claim below
    // it — this must stay green with the anchored regex and would go RED
    // if the anchor were reverted to indexOf().
    const card =
      '# Item 99 — fixture card\n\n' +
      '## Some other section\n\n' +
      'Its `## Rules implemented` block is generated from the rule-ownership mapping ' +
      'and should not be confused with the real heading below.\n\n' +
      '## Rules implemented\n\n' +
      '<!-- generated by docs/design/apply-rule-ownership.mjs - edits inside this block are overwritten -->\n\n' +
      '1 rule(s) from `docs/design/rules.json`.\n\n' +
      '| Design section | Rule ids |\n' +
      '|---|---|\n' +
      '| §1.1 | R-050 |\n\n' +
      '## Known gaps\n\n' +
      'None.\n';
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', card);
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-050\n');

    const res = runCheck(root);
    // R-050 must be recognised as claimed — if the anchor is reverted to
    // indexOf(), the prose mention wins, the real heading's claim is lost,
    // and R-050 shows up as a MODE 1 orphan (exit 1) instead.
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.doesNotMatch(res.stdout, /MODE 1/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MODE2_ENFORCE=true path: a card claim with no declaring test now exits 1', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-008')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-008'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing declared here\n');

    const res = spawnSync(
      'node',
      [
        SCRIPT,
        '--rules',
        join(root, 'docs/design/rules.json'),
        '--cards',
        join(root, 'docs/design/build-cards'),
        '--unclaimed',
        join(root, 'docs/design/rules-unclaimed.json'),
        '--tests',
        join(root, 'tests'),
      ],
      { encoding: 'utf8', env: { ...process.env, DESIGN_TRACEABILITY_MODE2_ENFORCE: 'true' } }
    );
    assert.equal(res.status, 1, res.stdout + res.stderr);
    assert.match(res.stdout, /MODE 2 \(ENFORCING\)/);
    assert.match(res.stdout, /R-008/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('real repo: the check parses the actual rules.json/cards/tests and never exits 2', () => {
  const res = spawnSync('node', [SCRIPT], { cwd: REPO_ROOT, encoding: 'utf8' });
  // A real finding (exit 1) is allowed and must be reported, never silenced.
  // Exit 2 would mean the check itself cannot even parse the repo's own
  // real files, which is a defect in the check.
  assert.notEqual(res.status, 2, res.stdout + res.stderr);
  assert.match(res.stdout, /\d+ rules?, \d+ claimed, \d+ orphan/i);
  // #469 mode 5 (per-card ownership) — every owned rule is claimed by its
  // owning card's own generated block on main, so this must be a clean pass,
  // not a skip. If this regresses to "MODE 5 — SKIPPED" the real
  // docs/design/rule-ownership.json stopped resolving next to the real
  // docs/design/rules.json (see resolveOptions()'s ownershipPath default).
  assert.match(res.stdout, /MODE 5 — \d+ owned rule\(s\) checked against their owning card\(s\), 0 gaps/);
});

// --- #469: mode 5, per-card ownership. -------------------------------------
// Mode 1's ANY-card semantics passed a card that dropped a rule it owns as
// long as some OTHER, non-owning card still mentioned the id (the real §7.6
// case: R-142..R-144 owned by items [2, 20]; item 20 could drop them while
// item 02's stale mention kept the gate green). These fixtures reproduce
// that shape generically and must FAIL where mode 1 alone would still PASS.

function ownershipJson(sections) {
  return JSON.stringify({ sections }, null, 2);
}

test('#469 mode 5: a card drops a rule it owns while another (non-owning) card still claims it -> exit 1', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-144', { section: '7.6 Fixture module boundary' })]));
    // Owned by items 2 AND 20 (own.sections[sec] is an array — a rule can
    // legitimately have more than one owning card, per rule-ownership.json's
    // real §7.6/§1.12 rows).
    writeFile(root, 'docs/design/rule-ownership.json', ownershipJson({ '7.6': [2, 20] }));
    // Item 02's card still claims it (the stale, non-owning mention).
    writeFile(root, 'docs/design/build-cards/item-02-fixture.md', cardBody('R-144'));
    // Item 20's card — the ACTUAL owner per rule-ownership.json — dropped it.
    writeFile(root, 'docs/design/build-cards/item-20-fixture.md', cardBody('(none)'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-144\n');

    const res = runCheck(root, ['--ownership', join(root, 'docs/design/rule-ownership.json')]);
    // Mode 1 alone (ANY-card) would still be exit 0 here — item 02's claim
    // means R-144 is "claimed by no card at all" is false. This is exactly
    // the hole #469 reported; mode 5 must catch what mode 1 cannot.
    assert.equal(res.status, 1, res.stdout + res.stderr);
    const out = res.stdout + res.stderr;
    assert.match(out, /MODE 5/);
    assert.match(out, /R-144/);
    assert.match(out, /item-20-fixture\.md/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('#469 mode 5: a hand-owned owning card is exempt from the per-card ownership requirement -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-145', { section: '7.6 Fixture module boundary' })]));
    writeFile(root, 'docs/design/rule-ownership.json', ownershipJson({ '7.6': [20] }));
    // Item 20 is the sole owner and does NOT claim R-145, but its "## Rules
    // implemented" block carries the #1106 hand-owned marker — the same
    // marker apply-rule-ownership.mjs treats as SKIPPED, not REFUSED. Mode 5
    // must give it the same exemption, or every hand-owned governance-rule
    // card in the real repo would start failing this gate.
    writeFile(
      root,
      'docs/design/build-cards/item-20-fixture.md',
      '# Item 20 — fixture card\n\n' +
        '## Rules implemented\n\n' +
        '<!-- hand-owned: not generated by apply-rule-ownership.mjs, see docs/design/apply-rule-ownership.mjs HAND_OWNED_MARKER -->\n\n' +
        'Hand-curated list, intentionally not R-145.\n\n' +
        '## Known gaps\n\nNone.\n'
    );
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: { 'R-145': 'hand-owned fixture' } }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-145\n');

    const res = runCheck(root, ['--ownership', join(root, 'docs/design/rule-ownership.json')]);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.doesNotMatch(res.stdout + res.stderr, /MODE 5 — \d+ rule\(s\) assigned/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('#469 mode 5: no rule-ownership.json at the resolved path -> SKIPPED, not a failure', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-146')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-146'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-146\n');
    // Deliberately no docs/design/rule-ownership.json written, and no
    // --ownership passed — resolveOptions() defaults it next to --rules.

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.match(res.stdout, /MODE 5 — SKIPPED/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Mode 4 fixtures: hash-drift needs REAL git history for a base ref. ---
// Each fixture below is a real "git init"-ed repo (not the temp dirs above,
// which are deliberately NOT git repos -- that absence is what proves modes
// 1-3 stay inert without --base, see the no-op test right below). autocrlf
// is pinned off so "git show" returns the exact bytes written to disk on
// Windows, which the byte-identical case depends on.

function git(cwd, args) {
  const res = spawnSync('git', args, { cwd, encoding: 'utf8' });
  if (res.status !== 0) {
    throw new Error('git ' + args.join(' ') + ' failed (' + res.status + '): ' + (res.stderr || res.stdout));
  }
  return res.stdout;
}

function initGitFixture(root) {
  git(root, ['init', '-q']);
  git(root, ['config', 'core.autocrlf', 'false']);
  git(root, ['config', 'user.email', 'fixture@example.com']);
  git(root, ['config', 'user.name', 'Fixture']);
}

function commitAll(root, message) {
  git(root, ['add', '-A']);
  git(root, ['commit', '-q', '-m', message]);
  return git(root, ['rev-parse', 'HEAD']).trim();
}

function runCheckAtBase(root, base, extraArgs = []) {
  return spawnSync(
    'node',
    [
      SCRIPT,
      '--rules',
      join(root, 'docs/design/rules.json'),
      '--cards',
      join(root, 'docs/design/build-cards'),
      '--unclaimed',
      join(root, 'docs/design/rules-unclaimed.json'),
      '--tests',
      join(root, 'tests'),
      '--base',
      base,
      ...extraArgs,
    ],
    { cwd: root, encoding: 'utf8' }
  );
}

test('mode 4 is inert without --base: a non-git fixture tree still exits 0', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-900')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-900'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-900\n');

    const res = runCheck(root); // no --base, no git init in root
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.doesNotMatch(res.stdout + res.stderr, /not a git repository/i);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4 without --base prints an explicit skip line, never a silent no-op', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-900')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-900'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-900\n');

    const res = runCheck(root); // no --base
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.match(
      res.stdout,
      /MODE 4 — SKIPPED \(no --base given\): hash drift was NOT compared/,
      res.stdout + res.stderr
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('--base given as an empty string -> exit 2, never the SKIPPED path', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-900')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-900'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-900\n');

    const res = runCheck(root, ['--base', '']);
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stderr, /--base was given with no ref value/);
    assert.doesNotMatch(res.stdout, /MODE 4 — SKIPPED/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('--base given as the final argument with no value -> exit 2, never the SKIPPED path', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-900')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-900'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-900\n');

    const res = runCheck(root, ['--base']);
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stderr, /--base was given with no ref value/);
    assert.doesNotMatch(res.stdout, /MODE 4 — SKIPPED/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: hash changed at HEAD, neither card nor test in the diff -> exit 1, names the id + card', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-101', { hash: 'aaa111111111' })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-101'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-101\n');
    const base = commitAll(root, 'base');

    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-101', { hash: 'bbb222222222' })]));
    commitAll(root, 'drift rules.json only');

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 1, res.stdout + res.stderr);
    const out = res.stdout + res.stderr;
    assert.match(out, /MODE 4/);
    assert.match(out, /R-101/);
    assert.match(out, /item-99-fixture\.md/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: same drift, but the owning CARD is in the diff -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-102', { hash: 'aaa111111111' })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-102'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-102\n');
    const base = commitAll(root, 'base');

    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-102', { hash: 'bbb222222222' })]));
    writeFile(
      root,
      'docs/design/build-cards/item-99-fixture.md',
      cardBody('R-102') + '\n<!-- touched to acknowledge the reworded rule -->\n'
    );
    commitAll(root, 'drift rules.json + touch the owning card');

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 0, res.stdout + res.stderr);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: same drift, but a DECLARING TEST is in the diff -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-103', { hash: 'aaa111111111' })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-103'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-103\n');
    const base = commitAll(root, 'base');

    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-103', { hash: 'bbb222222222' })]));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-103\n// re-checked against the reworded rule\n');
    commitAll(root, 'drift rules.json + touch the declaring test');

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 0, res.stdout + res.stderr);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: a NEW rule id at HEAD absent at base is not a drift -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-104', { hash: 'aaa111111111' })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-104'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-104\n');
    const base = commitAll(root, 'base');

    writeFile(
      root,
      'docs/design/rules.json',
      rulesJson([rule('R-104', { hash: 'aaa111111111' }), rule('R-204', { hash: 'ccc333333333' })])
    );
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-104, R-204'));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-104, R-204\n');
    commitAll(root, 'add a brand-new rule id');

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    // The summary still always prints compared/drifted counts (self-guard);
    // what it must NOT contain is a MODE 4 FAIL — R-204 (new at HEAD) is
    // simply outside the comparison, R-104 (unchanged) is not drifted.
    assert.doesNotMatch(res.stdout, /MODE 4 FAIL/);
    assert.match(res.stdout, /0 drifted/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: a rule RETIRED at HEAD is not a drift -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(
      root,
      'docs/design/rules.json',
      rulesJson([rule('R-105', { hash: 'aaa111111111' }), rule('R-106', { hash: 'zzz999999999' })])
    );
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-105, R-106'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-105, R-106\n');
    const base = commitAll(root, 'base');

    writeFile(
      root,
      'docs/design/rules.json',
      rulesJson([
        rule('R-105', { hash: 'aaa111111111' }),
        rule('R-106', { hash: 'yyy888888888', retired: true }),
      ])
    );
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-105'));
    // Drop the now-retired R-106 declaration too, so this fixture isolates
    // mode 4 (retirement is not a drift) from mode 3 (a test naming a
    // now-non-live id), which is a separate, already-covered failure mode.
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-105\n');
    commitAll(root, 'retire R-106');

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.doesNotMatch(res.stdout, /MODE 4 FAIL/);
    assert.match(res.stdout, /0 drifted/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: base rules.json unreadable (bad ref) -> exit 2, message names the ref', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-107')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-107'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-107\n');
    commitAll(root, 'base');

    const res = runCheckAtBase(root, 'this-ref-does-not-exist-12345');
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /this-ref-does-not-exist-12345/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 4: base and HEAD identical -> exit 0, summary says so explicitly', () => {
  const root = mkFixtureRoot();
  try {
    initGitFixture(root);
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-108', { hash: 'aaa111111111' })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-108'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-108\n');
    const base = commitAll(root, 'base');
    // No further commits: base and HEAD are the same commit, so the file on
    // disk is byte-identical to what "git show <base>:..." returns.

    const res = runCheckAtBase(root, base);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.match(res.stdout, /byte-identical/i);
    assert.match(res.stdout, /\d+ rule id\(s\) compared/);
    assert.match(res.stdout, /0 drifted/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// Regression, 2026-09-18 (#763): the id extractor was /R-\d+/ with no word
// boundary, so a prose word ENDING in "R-" plus digits was read as a rule id.
// A real test header — "implements: #762 (S8) review round 2 CRITICAL +
// MAJOR-4" — yielded the phantom id "R-4" out of the middle of "MAJOR-4",
// and mode 3 failed the PR gate for a rule nobody had declared. Live ids are
// always zero-padded to three digits (188 of 188 in rules.json at the time
// of this fix), so the boundary-anchored 3-digit form is exact, not a guess.
test('mode 3 regression: "MAJOR-4" in an implements header is NOT read as rule id R-4', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-003')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-003'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    // The exact shape that broke PR #763: a real rule id alongside prose that
    // contains "MAJOR-4". Only R-003 may be extracted.
    writeFile(
      root,
      'tests/unit/reclaim.test.mjs',
      IMPLEMENTS_TAG + 'R-003 -- #762 (S8) review round 2 CRITICAL + MAJOR-4\n'
    );

    const res = runCheck(root);
    const out = res.stdout + res.stderr;
    assert.equal(res.status, 0, `expected a clean pass, got exit ${res.status}:\n${out}`);
    assert.doesNotMatch(out, /R-4\b/, 'phantom id R-4 was extracted from "MAJOR-4"');
    assert.doesNotMatch(out, /MODE 3/, 'mode 3 fired on a header with no bad rule id');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
