// Self-test for scripts/ci/check-design-traceability.mjs (OD-52, §8.5).
// Each case below builds a tiny fixture tree in a temp dir and runs the REAL
// check script against it via a child process — the test never re-implements
// the check's parsing logic. Slice s1: failure modes 1-3 only (mode 4, the
// hash-drift check, is a later slice).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(__dirname, '..', 'check-design-traceability.mjs');
// Repo root, for the one case that runs against the real files.
const REPO_ROOT = join(__dirname, '..', '..', '..');

// This test file lives under scripts/ci/tests/, one of the check's own real
// scan roots — so a literal "// implements: R-xxx" string embedded verbatim
// in this source would be picked up by the check when it later scans the
// REAL repo (the last test case below runs the check against real files).
// Build the header out of parts so the raw source never contains the
// contiguous "// implements:" substring; the runtime STRING VALUE written to
// each fixture file is still exactly that text.
const IMPLEMENTS_TAG = ['/', '/', ' implements: '].join('');

function writeFile(root, relPath, content) {
  const full = join(root, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

function mkFixtureRoot() {
  return mkdtempSync(join(tmpdir(), 'design-traceability-'));
}

function rulesJson(rules) {
  return JSON.stringify({ rules }, null, 2);
}

function rule(id, opts = {}) {
  return {
    id,
    hash: opts.hash || 'deadbeef0000',
    section: opts.section || '1.1 Fixture section',
    kind: opts.kind || 'prose',
    text: opts.text || 'A fixture rule.',
    first_seen: '2026-09-10',
    retired: !!opts.retired,
  };
}

function cardBody(idsLine) {
  return (
    '# Item 99 — fixture card\n\n' +
    '## Rules implemented\n\n' +
    '<!-- generated by docs/design/apply-rule-ownership.mjs - edits inside this block are overwritten -->\n\n' +
    '1 rule(s) from `docs/design/rules.json`.\n\n' +
    '| Design section | Rule ids |\n' +
    '|---|---|\n' +
    '| §1.1 | ' +
    idsLine +
    ' |\n\n' +
    '## Known gaps\n\n' +
    'None.\n'
  );
}

function runCheck(root, extraArgs = []) {
  return spawnSync(
    'node',
    [
      SCRIPT,
      '--rules',
      join(root, 'docs/design/rules.json'),
      '--cards',
      join(root, 'docs/design/build-cards'),
      '--unclaimed',
      join(root, 'docs/design/rules-unclaimed.json'),
      '--tests',
      join(root, 'tests'),
      ...extraArgs,
    ],
    { encoding: 'utf8' }
  );
}

test('mode 1: a live rule claimed by no card and not unclaimed -> exit 1, names the id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-001')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-999-not-real'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing here\n');

    const res = runCheck(root);
    assert.equal(res.status, 1, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /R-001/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 2: a card claims an id no test declares -> exit 0 (reporting mode), names card + id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-002')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-002'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing declared here\n');

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.match(res.stdout, /R-002/);
    assert.match(res.stdout, /item-99-fixture\.md/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('mode 3: a test declares R-999 which is not live -> exit 1, names the test file + id', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-003')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-003'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/bar.test.mjs', IMPLEMENTS_TAG + 'R-003, R-999\n');

    const res = runCheck(root);
    assert.equal(res.status, 1, res.stdout + res.stderr);
    const out = res.stdout + res.stderr;
    assert.match(out, /R-999/);
    assert.match(out, /bar\.test\.mjs/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('self-guard: zero live rules is a FAIL, never a pass -> exit 2', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-004', { retired: true })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-004'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-004\n');

    const res = runCheck(root);
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /zero live rules/i);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('clean fixture tree -> exit 0', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-005'), rule('R-006', { retired: true })]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-005'));
    writeFile(
      root,
      'docs/design/rules-unclaimed.json',
      JSON.stringify({ unclaimed: { 'R-007': 'not a real rule, just proving unclaimed is honored' } })
    );
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-005\n');

    const res = runCheck(root);
    assert.equal(res.status, 0, res.stdout + res.stderr);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MAJOR 1 regression: zero surviving test roots -> exit 2, never a silent PASS', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-777')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-777'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    // Deliberately do NOT create the tests root — this reproduces the
    // reviewer's finding: `--tests <nonexistent>` used to print
    // "1 rules, 1 claimed, 0 orphans ... PASS" and exit 0, silently
    // disarming mode 3 for the whole population of test declarations.
    const res = spawnSync(
      'node',
      [
        SCRIPT,
        '--rules',
        join(root, 'docs/design/rules.json'),
        '--cards',
        join(root, 'docs/design/build-cards'),
        '--unclaimed',
        join(root, 'docs/design/rules-unclaimed.json'),
        '--tests',
        join(root, 'tests-does-not-exist'),
      ],
      { encoding: 'utf8' }
    );
    assert.equal(res.status, 2, res.stdout + res.stderr);
    assert.match(res.stdout + res.stderr, /zero test roots/i);
    assert.match(res.stdout + res.stderr, /tests-does-not-exist/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MAJOR 2 regression: heading anchor recognises the real heading even when prose mentions it first', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-050')]));
    // Mirrors the real item-19 card bug: prose ABOVE the real heading
    // mentions the heading text in backticks, mid-document, before the
    // actual "## Rules implemented" heading. A plain indexOf() finds the
    // prose mention instead of the real heading and loses the claim below
    // it — this must stay green with the anchored regex and would go RED
    // if the anchor were reverted to indexOf().
    const card =
      '# Item 99 — fixture card\n\n' +
      '## Some other section\n\n' +
      'Its `## Rules implemented` block is generated from the rule-ownership mapping ' +
      'and should not be confused with the real heading below.\n\n' +
      '## Rules implemented\n\n' +
      '<!-- generated by docs/design/apply-rule-ownership.mjs - edits inside this block are overwritten -->\n\n' +
      '1 rule(s) from `docs/design/rules.json`.\n\n' +
      '| Design section | Rule ids |\n' +
      '|---|---|\n' +
      '| §1.1 | R-050 |\n\n' +
      '## Known gaps\n\n' +
      'None.\n';
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', card);
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', IMPLEMENTS_TAG + 'R-050\n');

    const res = runCheck(root);
    // R-050 must be recognised as claimed — if the anchor is reverted to
    // indexOf(), the prose mention wins, the real heading's claim is lost,
    // and R-050 shows up as a MODE 1 orphan (exit 1) instead.
    assert.equal(res.status, 0, res.stdout + res.stderr);
    assert.doesNotMatch(res.stdout, /MODE 1/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('MODE2_ENFORCE=true path: a card claim with no declaring test now exits 1', () => {
  const root = mkFixtureRoot();
  try {
    writeFile(root, 'docs/design/rules.json', rulesJson([rule('R-008')]));
    writeFile(root, 'docs/design/build-cards/item-99-fixture.md', cardBody('R-008'));
    writeFile(root, 'docs/design/rules-unclaimed.json', JSON.stringify({ unclaimed: {} }));
    writeFile(root, 'tests/unit/foo.test.mjs', '// nothing declared here\n');

    const res = spawnSync(
      'node',
      [
        SCRIPT,
        '--rules',
        join(root, 'docs/design/rules.json'),
        '--cards',
        join(root, 'docs/design/build-cards'),
        '--unclaimed',
        join(root, 'docs/design/rules-unclaimed.json'),
        '--tests',
        join(root, 'tests'),
      ],
      { encoding: 'utf8', env: { ...process.env, DESIGN_TRACEABILITY_MODE2_ENFORCE: 'true' } }
    );
    assert.equal(res.status, 1, res.stdout + res.stderr);
    assert.match(res.stdout, /MODE 2 \(ENFORCING\)/);
    assert.match(res.stdout, /R-008/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('real repo: the check parses the actual rules.json/cards/tests and never exits 2', () => {
  const res = spawnSync('node', [SCRIPT], { cwd: REPO_ROOT, encoding: 'utf8' });
  // A real finding (exit 1) is allowed and must be reported, never silenced.
  // Exit 2 would mean the check itself cannot even parse the repo's own
  // real files, which is a defect in the check.
  assert.notEqual(res.status, 2, res.stdout + res.stderr);
  assert.match(res.stdout, /\d+ rules?, \d+ claimed, \d+ orphan/i);
});
