// scripts/tests/apply-rule-ownership.test.mjs
//
// Issue #905: `apply-rule-ownership.mjs --apply` treated the whole span between the
// "## Rules implemented" heading and the "## Known gaps" heading as its own, so a hand-written
// section a card author added AFTER the generated table (item-21's real
// "## Status of this card's corrections (2026-09-10, implementation session)", 56 lines) was
// silently deleted the next time anyone regenerated the card. This drives the REAL
// spliceGeneratedBlock()/buildBlock() (not a re-implementation) against exactly that real text,
// plus the ordinary fresh-card and hand-written-card cases, with no file I/O.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spliceGeneratedBlock, buildBlock, MARKER, END_MARKER, HAND_OWNED_MARKER } from '../../docs/design/apply-rule-ownership.mjs';

const RULE = (id, section) => ({ id, section });

test('a fresh card with no existing block gets one appended, ending in the end marker', () => {
  const md = '# item-99\n\nSome prose.\n';
  const block = buildBlock([RULE('R-001', '§2.1')]);
  const { next, changed, refused } = spliceGeneratedBlock(md, block, 'item-99.md');
  assert.equal(refused, null);
  assert.equal(changed, true);
  assert.ok(next.includes('## Rules implemented'));
  assert.ok(next.includes(MARKER));
  assert.ok(next.includes(END_MARKER));
  assert.ok(next.includes('## Known gaps'));
  // Block ends before "## Known gaps": order is heading -> marker -> table -> end marker -> gaps.
  assert.ok(next.indexOf(END_MARKER) < next.indexOf('## Known gaps'));
});

test('item-21\'s real hand-written section survives a regeneration once the end marker is present', () => {
  const oldBlock = [
    '## Rules implemented',
    '',
    MARKER,
    '',
    '10 rule(s) from `docs/design/rules.json`, generated by',
    '`node docs/design/apply-rule-ownership.mjs --apply` from `rule-ownership.json`.',
    '',
    '| Design section | Rule ids |',
    '|---|---|',
    '| §2.11 | R-081, R-082 |',
    '',
    END_MARKER,
  ].join('\n');
  const handWritten = [
    '',
    "## Status of this card's corrections (2026-09-10, implementation session)",
    '',
    'This card was written against an earlier `§2.11` and flags three places as "the design is wrong".',
    '**All three have since been corrected in the design itself**.',
  ].join('\n');
  const md = [
    '# item-21',
    '',
    'Some interfaces prose.',
    '',
    oldBlock,
    handWritten,
    '',
    '## Known gaps',
    '',
    '- nothing yet',
    '',
  ].join('\n');

  const newBlock = buildBlock([RULE('R-081', '§2.11'), RULE('R-082', '§2.11'), RULE('R-232', '§2.11')]);
  const { next, changed, refused } = spliceGeneratedBlock(md, newBlock, 'item-21-read-side.md');
  assert.equal(refused, null);
  assert.equal(changed, true);
  // The hand-written section text is present verbatim, in full (all 5 lines / both sentences).
  assert.ok(next.includes("## Status of this card's corrections (2026-09-10, implementation session)"));
  assert.ok(next.includes('All three have since been corrected in the design itself'));
  // The new rule table replaced the old one.
  assert.ok(next.includes('R-232'));
  assert.ok(!next.includes('| §2.11 | R-081, R-082 |'));
  // "## Known gaps" and everything after it is untouched.
  assert.ok(next.includes('## Known gaps'));
  assert.ok(next.includes('- nothing yet'));
});

test('a pre-migration card (marker present, no end marker) is REFUSED, not silently rewritten (item-21 as it really is today)', () => {
  const legacyBlock = [
    '## Rules implemented',
    '',
    MARKER,
    '',
    '10 rule(s) from `docs/design/rules.json`, generated by',
    '`node docs/design/apply-rule-ownership.mjs --apply` from `rule-ownership.json`.',
    '',
    '| Design section | Rule ids |',
    '|---|---|',
    '| §2.11 | R-081, R-082, R-083, R-085, R-087, R-162, R-163, R-164, R-232, R-233 |',
  ].join('\n');
  const md = [
    '# item-21',
    '',
    legacyBlock,
    '',
    "## Status of this card's corrections (2026-09-10, implementation session)",
    '',
    'This card was written against an earlier `§2.11`...',
    '',
    '## Known gaps',
    '',
    '- nothing yet',
    '',
  ].join('\n');

  const newBlock = buildBlock([RULE('R-081', '§2.11')]);
  const { next, changed, refused } = spliceGeneratedBlock(md, newBlock, 'item-21-read-side.md');
  assert.ok(refused, 'expected a refusal reason');
  assert.match(refused, /end marker/i);
  assert.equal(changed, false);
  assert.equal(next, md, 'card must be left byte-for-byte untouched on refusal');
});

test('a rules block with no generator marker at all (hand-written) is REFUSED', () => {
  const md = [
    '# item-1',
    '',
    '## Rules implemented',
    '',
    'Hand-typed: R-001, R-002.',
    '',
    '## Known gaps',
    '',
    '- none',
    '',
  ].join('\n');
  const newBlock = buildBlock([RULE('R-001', '§1')]);
  const { next, changed, refused } = spliceGeneratedBlock(md, newBlock, 'item-1.md');
  assert.ok(refused);
  assert.match(refused, /written by hand/i);
  assert.equal(changed, false);
  assert.equal(next, md);
});

test('#1106: a rules block carrying the hand-owned marker is SKIPPED, never refused and never rewritten', () => {
  const md = [
    '# item-24',
    '',
    '## Rules implemented',
    '',
    HAND_OWNED_MARKER,
    '',
    '- `defect-fix-contract.md` - RCA, class, failing test first, fix at class level.',
    '- `ist-timezone.md` - the window is evaluated on an IST calendar day.',
    '',
    '## Known gaps',
    '',
    '- none',
    '',
  ].join('\n');
  const newBlock = buildBlock([RULE('R-158', '§1.12')]);
  const { next, changed, refused, skipped } = spliceGeneratedBlock(md, newBlock, 'item-24-stage-gate-deadlock.md');
  assert.equal(refused, null);
  assert.equal(changed, false);
  assert.equal(skipped, true);
  assert.equal(next, md, 'card must be left byte-for-byte untouched when hand-owned');
  assert.ok(!next.includes('R-158'), 'the generated block must never have been spliced in');
});

test('re-running with no change produces changed=false (idempotent)', () => {
  const block = buildBlock([RULE('R-001', '§2.1')]);
  const md = '# item-99\n\nSome prose.\n\n' + block + '\n\n## Known gaps\n\nNone recorded yet.\n';
  const { changed, refused } = spliceGeneratedBlock(md, block, 'item-99.md');
  assert.equal(refused, null);
  assert.equal(changed, false);
});
